#!/bin/bash

R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"

function customize() {
	sudo apt update
	if [[ $(command -v plank) ]]; then
	echo "${G}Plank is already installed .."${W}
        sleep .5
        clear
   else
	   clear
	   sleep 1
	   echo "${G}Plank not found.Installing now.."${W}
	   echo
	   sudo apt install plank -y
	fi
mkdir /home/kali/.config/autostart/
        touch /home/kali/.config/autostart/plank.desktop
        echo "[Desktop Entry]" >>/home/kali/.config/autostart/plank.desktop
        echo "Type=Application" >>/home/kali/.config/autostart/plank.desktop
        echo "Name=Plank" >>/home/kali/.config/autostart/plank.desktop
        echo "Exec=plank" >>/home/kali/.config/autostart/plank.desktop
        chmod +x /home/kali/.config/autostart/plank.desktop
	sudo apt install zsh zsh-autosuggestions zsh-syntax-highlighting -y
    cp /etc/skel/.zshrc ~/
    sudo chsh -s $(which zsh) $(whoami)
}
function theme_setup() {
        sudo apt install git -y
	git clone --depth=1 https://github.com/vinceliuice/WhiteSur-gtk-theme /home/${user}/WhiteSur-gtk-theme
	sudo chmod +x /home/${user}/WhiteSur-gtk-theme/install.sh
        sudo bash /home/${user}/WhiteSur-gtk-theme/install.sh
	sleep 2
dbus-launch xfconf-query -c xfce4-desktop -np '/desktop-icons/style' -t 'int' -s '0'
sleep 10
dbus-launch xfconf-query -c xsettings -p /Net/ThemeName -s "WhiteSur-Light"
}
function setup_plank() {
	banner
	gsettings set net.launchpad.plank.dock.settings:/net/launchpad/plank/docks/dock1/ theme 'Gtk+'
	gsettings set net.launchpad.plank.dock.settings:/net/launchpad/plank/docks/dock1/ zoom-enabled true
}
function app_menu() {
	banner
	sudo apt install rofi -y
	sudo apt install wget -y
	mkdir -p ~/.config/rofi
        rofi -dump-config > ~/.config/rofi/config.rasi
	cd ~
	wget https://raw.githubusercontent.com/sabamdarif/modded-kali/main/image/application-menu.png
	wget https://raw.githubusercontent.com/sabamdarif/modded-kali/main/setup/style.rasi
	mv style.rasi application-menu.png ~/.config/rofi
	echo "#!/usr/bin/env bash
	## Run
	rofi \
    -show drun \
    -theme /home/kali/.config/rofi/style.rasi" >> /home/kali/.config/rofi/launcher.sh
	touch appsearch.desktop
echo "[Desktop Entry]
Name=Application Search
Exec=bash /home/kali/.config/rofi/launcher.sh
Icon=/home/kali/.config/rofi/application-menu.png
Type=Application
Terminal=false
StartupNotify=false" >> appsearch.desktop
mkdir ~/.local/share/applications
mv appsearch.desktop ~/.local/share/applications/
chmod +x ~/.local/share/applications/appsearch.desktop
mkdir /home/kali/.config/plank/dock1/launchers/
cp ~/.local/share/applications/appsearch.desktop /home/kali/Desktop/appsearch.desktop
touch /home/kali/.config/plank/dock1/launchers/appsearch.dockitem
echo "[PlankDockItemPreferences]
Launcher=file:///home/kali/.local/share/applications/appsearch.desktop" >> /home/kali/.config/plank/dock1/launchers/appsearch.dockitem
clear
echo "${G} setup successfull.."${W}

customize
theme_setup
app_menu

