#!/bin/bash
R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"

function package() {
    echo -e "${R} [${W}-${R}]${C} Checking required packages..."${W}
    sudo apt update -y
    sudo apt install sudo -y
    sudo dpkg --configure -a
    packs=(sudo wget curl nano kali-menu kali-linux-core git keyboard-configuration qterminal librsvg2-common menu kali-themes inetutils-tools dialog tightvncserver tigervnc-standalone-server tigervnc-tools dbus-x11 )
    sudo dpkg --configure -a
    for hulu in "${packs[@]}"; do
        type -p "$hulu" &>/dev/null || {
            echo -e "\n${R} [${W}-${R}]${G} Installing package : ${Y}$hulu${C}"${W}
            sudo apt-get install "$hulu" -y --no-install-recommends
        }
    done
    sudo apt update -y
}

function xfce_install() {
echo -e "${R} [${W}-${R}]${C} Installing XFCE DESKTOP"${W}
	apt update
       sudo apt install xfce4* -y
       sudo apt install grub-efi* -y
       echo -e "${R} [${W}-${R}]${C} Setting up VNC Server..."${W}
  if [[ ! -d "$HOME/.vnc" ]]; then
        mkdir -p "$HOME/.vnc"
    fi
    echo "export DISPLAY=":1"" >> /etc/profile
    echo "export PULSE_SERVER=127.0.0.1" >> /etc/profile
    source /etc/profile
}

function extra_things() {
	sudo apt install firefox-esr -y
        DISPLAY=:1 firefox &
        sleep 10
        pkill -f firefox
        sleep 1
        sudo apt install wget -y
        wget -O $(find /home/kali/.mozilla/firefox -name *.default-esr)/user.js https://raw.githubusercontent.com/sabamdarif/nethunter-best/main/others/user.js
}

function get-app-menu() {
       cd ~
       apt install wget -y
       wget https://raw.githubusercontent.com/sabamdarif/nethunter-best/main/appmenu-installer/install-app-menu
       mv install-app-menu /home/kali/install-app-menu
       chmod +x /home/kali/install-app-menu
       rm /home/kali/install-kali-desktop
}

xfce_install
package
get-app-menu
